@startuml

:Idrettsutøver:

Idrettsutøver -up-> (lage bruker)
Idrettsutøver -up-> (logge seg inn)
Idrettsutøver --> (melde seg inn/ut i lag)
Idrettsutøver --> (se andre medlemmer i lag)
Idrettsutøver --> (se kommende arangementer)
Idrettsutøver -right-> (se resultater)
Idrettsutøver -left-> (se melde seg på/av arangementer)
Idrettsutøver -left-> (betale påmeldings avgift)
Idrettsutøver -right-> (se påmeldte utøvere)

@enduml