@startuml
class user{
    -String username,password,epost-adresse,fornavn,etternavn
    -int: user-kode
}
interface organisasjon{
    -String: organisasjons_navn
    -Int: orginasjosjons_Nr
    -String: epostadresse.
    -String: post_sted
    -String: Post_nr
    -ArrayList<user>: ansatte
}

class idrettsutover{
    -idrettsLag: lag
    -ArrayList<arrangement>: deltatteArrangement
    -ArrayList<arrangement>: paameldteArrangement
    -ArrayList<resultat>: resultater
}


class idrettsLag{
    -String: lagKode
    -lagstyre: lagLeder
    -forbund: forbund
    -idrettsutover: lagKaptein
    -ArrayList<idrettsutover>: medlemmer
    -ArrayList<arrangement>: kommende_arrangementer
    -ArrayList<arrangement>: deltatte_arrangementer
    -ArrayList<resultat>: resultater
}


class lagstyrer{
     -idrettsLag: lag
     -String: StillingsBeskrivelse

}


class forbund{
    -forbundsAnnsatt: forbundsLeder
    -ArrayList<forbundsAnnsatt>: ansatte
}
class forbundsAnnsatt{
}
class arrangement
class admin
class resultat


idrettsutover -up-|> user
idrettsutover -left-> idrettsLag
idrettsutover -up-o resultat
idrettsutover -right-o arrangement

idrettsLag .up.|> organisasjon
idrettsLag --o idrettsutover
idrettsLag -right-o lagstyrer
idrettsLag -right-> lagstyrer
idrettsLag --o arrangement
idrettsLag -left-> forbund
idrettsLag -right-o resultat


lagstyrer -up-|> user
lagstyrer --> idrettsLag


forbund --o forbundsAnnsatt
forbund --> forbundsAnnsatt

forbundsAnnsatt -up-|> user
admin -left-|> user


forbund .up.|> organisasjon
@enduml